### ISSUE TITLE
Does this package support netcoreapp2.2?

### ISSUE THREAD

**Issue by rsibanez89** [Daniel15/prometheus-net.SystemMetrics#2]
Does this package support netcoreapp2.2 or is it just for netcoreapp3.1?

**Comment by Daniel15** [comment]
I've only tested it with .NET Core 3.x myself, however it may be possible to build it for 2.2 as well. You could try build it for 2.2 and see if it works? Feel free to submit a PR adding .NET Core 2.2 support if you like.

**Comment by Daniel15** [comment]
As per https://docs.microsoft.com/en-us/dotnet/standard/net-standard, .NET Standard 2.0 (which this package is built for) supports .NET Core 2.0, so no changes should be necessary.

**Comment by Daniel15** [comment]
Actually, I do have some 3.x deps... Maybe I can lower the version numbers.

**Comment by Daniel15** [comment]
Upon further investigation, .NET Core 2.2 is EOL now (https://dotnet.microsoft.com/platform/support/policy/dotnet-core) so I won't be adding direct support for it. Since the package is targeting .NET Standard 2.0, it should work though.
