### ISSUE TITLE
Globalization Invariant Mode Problem on .NET 6

### ISSUE THREAD

**Issue by bartoccioni** [Daniel15/prometheus-net.SystemMetrics#5]
Hello,
using prometheus-net.SystemMetrics on .NET 6 with Globalization Invariant Mode lead to a runtime exception due to the bug fixed on this PR https://github.com/dotnet/runtime/pull/65414 until the release of a NET version that fix this problem i've used the following partial workaround:

            //Workaround for the .NET 6 problem instantiating PerformanceCounter(for WindowsCpuUsageCollector) in invariant culture on Windows
            // https://github.com/dotnet/runtime/pull/65414 Fix PerformanceCounter's when running with Globalization Invariant Mode
            if (System.Globalization.CultureInfo.CurrentCulture == System.Globalization.CultureInfo.InvariantCulture && RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                services.AddSystemMetrics(registerDefaultCollectors: false);
                services.AddSystemMetricCollector<DiskCollector>();
                services.AddSystemMetricCollector<WindowsMemoryCollector>();
                services.AddSystemMetricCollector<LoadAverageCollector>();
                services.AddSystemMetricCollector<NetworkCollector>();
            }
            else
            {
                services.AddSystemMetrics();
            }

Ofc the CpuUsage counters are not available on Windows until the fix will be released, hope this could help.

Regards

Pietro

**Comment by Daniel15** [comment]
Hmm... The upstream bug is closed, but I'm still seeing this in .NET 8.0 🤔. I'll have to dig into this further.

**Comment by Daniel15** [comment]
Resolved in System.Diagnostics.PerformanceCounter - no changes in this library required. I'm going to wrap the initialization in a try-catch so that one collector throwing an error doesn't break the whole app.
